export interface Product {
  id: string;
  name: string;
  description: string;
  images: string[];
  pricePerUnit: number;
  pricePerPair?: number;
  categorySlug: string;
  features?: string[];
  specs?: { label: string; value: string }[];
}

export const products: Product[] = [
  // Komplett-Sets
  {
    id: 'komplett-set-small',
    name: 'Komplett-Set Small',
    description: 'Perfekt für Veranstaltungen bis 100 Personen. Enthält PA-System, Mischpult, Mikrofone und Basis-Beleuchtung.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 250,
    categorySlug: 'komplett-sets',
    features: ['PA bis 100 Personen', '16-Kanal Mischpult', '2 Funkmikrofone', 'Basis-Lichtset'],
  },
  {
    id: 'komplett-set-medium',
    name: 'Komplett-Set Medium',
    description: 'Ideal für Veranstaltungen bis 300 Personen. Erweiterte Ausstattung mit besserem Sound und professioneller Beleuchtung.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 450,
    categorySlug: 'komplett-sets',
    features: ['PA bis 300 Personen', '24-Kanal Mischpult', '4 Funkmikrofone', 'LED-Spots + Moving Heads'],
  },
  {
    id: 'komplett-set-large',
    name: 'Komplett-Set Large',
    description: 'Premium-Ausstattung für große Events bis 500 Personen. Professionelles Line Array System mit umfangreicher Lichttechnik.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 750,
    categorySlug: 'komplett-sets',
    features: ['PA bis 500 Personen', '32-Kanal Digital Mixer', '6 Funkmikrofone', 'Vollständige Lichtshow'],
  },
  {
    id: 'komplett-set-wedding',
    name: 'Hochzeits-Paket',
    description: 'Speziell für Hochzeiten zusammengestellt. Eleganter Sound und dezente Beleuchtung für einen unvergesslichen Tag.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 350,
    categorySlug: 'komplett-sets',
    features: ['PA bis 150 Personen', 'Elegantes Design', 'Headset-Mikrofon für Trauung', 'Warmes Ambiente-Licht'],
  },
  {
    id: 'komplett-set-outdoor',
    name: 'Outdoor-Event Paket',
    description: 'Robustes Equipment für Outdoor-Veranstaltungen. Wetterfest und leistungsstark für jeden Außenbereich.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 550,
    categorySlug: 'komplett-sets',
    features: ['Wetterfeste PA-Anlage', 'Stromerzeuger inklusive', 'Robuste Mikrofone', 'LED-Beleuchtung'],
  },

  // PA-Anlagen
  {
    id: 'pa-small',
    name: 'PA-Anlage Small',
    description: 'Kompakte PA-Anlage für kleinere Räume und Veranstaltungen bis 100 Personen.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 120,
    pricePerPair: 200,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '500W RMS' },
      { label: 'Personen', value: 'bis 100' },
      { label: 'Aktiv/Passiv', value: 'Aktiv' },
    ],
  },
  {
    id: 'pa-medium',
    name: 'PA-Anlage Medium',
    description: 'Mittlere PA-Anlage mit kraftvollem Sound für Veranstaltungen bis 300 Personen.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 180,
    pricePerPair: 300,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '1000W RMS' },
      { label: 'Personen', value: 'bis 300' },
      { label: 'Aktiv/Passiv', value: 'Aktiv' },
    ],
  },
  {
    id: 'pa-large',
    name: 'PA-Anlage Large',
    description: 'Professionelle PA-Anlage für große Veranstaltungen bis 500 Personen mit Line Array Technologie.',
    images: ['/images/palive2-1920w.webp'],
    pricePerUnit: 350,
    pricePerPair: 600,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '2000W RMS' },
      { label: 'Personen', value: 'bis 500' },
      { label: 'Aktiv/Passiv', value: 'Aktiv' },
    ],
  },
  {
    id: 'pa-subwoofer',
    name: 'Subwoofer System',
    description: 'Kraftvoller Subwoofer für tiefe Bässe. Perfekt in Kombination mit unseren PA-Anlagen.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 150,
    pricePerPair: 250,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '800W RMS' },
      { label: 'Frequenzbereich', value: '40-200 Hz' },
      { label: 'Typ', value: 'Aktiv' },
    ],
  },
  {
    id: 'pa-monitor',
    name: 'Monitor Boxen',
    description: 'Bühnenmonitore für professionelle Rückmischung. Ideal für Bands und Live-Performances.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 80,
    pricePerPair: 140,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '300W RMS' },
      { label: 'Typ', value: 'Aktiv' },
      { label: 'Anwendung', value: 'Bühnen-Monitoring' },
    ],
  },

  // Mischpulte
  {
    id: 'mixer-analog-16',
    name: 'Analog Mixer 16-Kanal',
    description: 'Zuverlässiges Analog-Mischpult mit 16 Eingangskanälen. Ideal für einfache bis mittlere Veranstaltungen.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'mischpulte',
    specs: [
      { label: 'Kanäle', value: '16' },
      { label: 'Typ', value: 'Analog' },
      { label: 'Effekte', value: 'Integriert' },
    ],
  },
  {
    id: 'mixer-analog-24',
    name: 'Analog Mixer 24-Kanal',
    description: 'Professionelles 24-Kanal Analog-Mischpult mit erweiterten Features für größere Events.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 120,
    categorySlug: 'mischpulte',
    specs: [
      { label: 'Kanäle', value: '24' },
      { label: 'Typ', value: 'Analog' },
      { label: 'Subgruppen', value: '4' },
    ],
  },
  {
    id: 'mixer-digital-32',
    name: 'Digital Mixer 32-Kanal',
    description: 'Modernes Digital-Mischpult mit Touchscreen-Bedienung und professionellen Effekten.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 200,
    categorySlug: 'mischpulte',
    specs: [
      { label: 'Kanäle', value: '32' },
      { label: 'Typ', value: 'Digital' },
      { label: 'Display', value: 'Touchscreen' },
    ],
  },
  {
    id: 'mixer-digital-rack',
    name: 'Digital Mixer Rack',
    description: 'Rackmount-Digital-Mixer für feste Installationen oder kompakte Setups.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 250,
    categorySlug: 'mischpulte',
    specs: [
      { label: 'Kanäle', value: '32' },
      { label: 'Typ', value: 'Digital Rack' },
      { label: 'Steuerung', value: 'iPad/PC' },
    ],
  },
  {
    id: 'mixer-dj',
    name: 'DJ-Mixer',
    description: 'Professioneller DJ-Mixer mit Crossfader und erweiterten Mixing-Features.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 100,
    categorySlug: 'mischpulte',
    specs: [
      { label: 'Kanäle', value: '4' },
      { label: 'Typ', value: 'DJ Mixer' },
      { label: 'Features', value: 'Crossfader, FX' },
    ],
  },

  // LED Spots
  {
    id: 'led-spot-par',
    name: 'LED PAR 64',
    description: 'Energieeffiziente LED PAR-Lampe mit RGB-Farbspektrum. Ideal für Bühnen- und Event-Beleuchtung.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 15,
    categorySlug: 'led-spots',
    specs: [
      { label: 'Leistung', value: '60W' },
      { label: 'Farben', value: 'RGB/RGBW' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'led-spot-wash',
    name: 'LED Wash 300',
    description: 'Weitwinkliger LED Wash für gleichmäßige Raumausleuchtung. Perfekt für Atmosphäre und Farbstimmungen.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 25,
    categorySlug: 'led-spots',
    specs: [
      { label: 'Leistung', value: '300W' },
      { label: 'Beam-Winkel', value: '60°' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'led-spot-bar',
    name: 'LED Bar 4x10W',
    description: 'Kompakte LED-Bar mit 4 Einzelmodulen. Vielseitig einsetzbar für kleine bis mittlere Räume.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 20,
    categorySlug: 'led-spots',
    specs: [
      { label: 'Leistung', value: '4x10W' },
      { label: 'Farben', value: 'RGBW' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'led-spot-uplight',
    name: 'LED Uplight',
    description: 'Standlicht für indirekte Beleuchtung. Erzeugt elegante Lichtakzente an Wänden und Decken.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 12,
    categorySlug: 'led-spots',
    specs: [
      { label: 'Leistung', value: '18W' },
      { label: 'Farben', value: 'RGB' },
      { label: 'Anwendung', value: 'Uplighting' },
    ],
  },
  {
    id: 'led-spot-panel',
    name: 'LED Panel 100W',
    description: 'Großflächiges LED-Panel für gleichmäßige, weiche Beleuchtung. Ideal für Hintergrundbeleuchtung.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 30,
    categorySlug: 'led-spots',
    specs: [
      { label: 'Leistung', value: '100W' },
      { label: 'Größe', value: '50x50cm' },
      { label: 'DMX', value: 'Ja' },
    ],
  },

  // Moving Heads
  {
    id: 'moving-head-150',
    name: 'Moving Head 150W',
    description: 'Professioneller Moving Head mit 150W Leistung. Präzise Bewegungen und vielfältige Gobo-Optionen.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 45,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Leistung', value: '150W' },
      { label: 'Gobos', value: '15 fest + Rotating' },
      { label: 'Pan/Tilt', value: '540°/270°' },
    ],
  },
  {
    id: 'moving-head-230',
    name: 'Moving Head 230W',
    description: 'Hochleistungs-Moving Head mit 230W für eindrucksvolle Lichtshows auf großen Bühnen.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 65,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Leistung', value: '230W' },
      { label: 'Gobos', value: '20 fest + Rotating' },
      { label: 'Pan/Tilt', value: '540°/270°' },
    ],
  },
  {
    id: 'moving-head-beam',
    name: 'Beam Moving Head 200W',
    description: 'Scharf gebündelter Beam Moving Head für dramatische Lichtstrahlen und Laser-ähnliche Effekte.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 55,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Leistung', value: '200W' },
      { label: 'Beam-Winkel', value: 'Narrow Beam' },
      { label: 'Stroboskop', value: 'Ja' },
    ],
  },
  {
    id: 'moving-head-wash',
    name: 'Wash Moving Head 200W',
    description: 'Weitwinkliger Wash Moving Head für gleichmäßige Ausleuchtung mit Bewegungsmöglichkeit.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Leistung', value: '200W' },
      { label: 'Beam-Winkel', value: '50°' },
      { label: 'Pan/Tilt', value: '540°/270°' },
    ],
  },
  {
    id: 'moving-head-compact',
    name: 'Compact Moving Head',
    description: 'Kompakter Moving Head für kleinere Veranstaltungen. Leichtgewichtig aber professionell.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 35,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Leistung', value: '120W' },
      { label: 'Gewicht', value: '8kg' },
      { label: 'Gobos', value: '10 fest' },
    ],
  },

  // Mikrofone
  {
    id: 'mic-handheld',
    name: 'Handheld Funkmikrofon',
    description: 'Professionelles Handheld-Funkmikrofon für Vokalisten und Moderatoren. Klarer, natürlicher Sound.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 30,
    categorySlug: 'mikrofone',
    specs: [
      { label: 'Typ', value: 'Handheld Funk' },
      { label: 'Frequenz', value: 'UHF' },
      { label: 'Reichweite', value: 'bis 100m' },
    ],
  },
  {
    id: 'mic-headset',
    name: 'Headset-Mikrofon',
    description: 'Komfortables Headset-Mikrofon für Vorträge und Präsentationen. Freihändige Nutzung.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 35,
    categorySlug: 'mikrofone',
    specs: [
      { label: 'Typ', value: 'Headset Funk' },
      { label: 'Anwendung', value: 'Vorträge/Moderation' },
      { label: 'Komfort', value: 'Leichtgewichtig' },
    ],
  },
  {
    id: 'mic-lapel',
    name: 'Lapel-Mikrofon',
    description: 'Diskretes Lavalier-Mikrofon für Gespräche und Interviews. Kleine, unscheinbare Bauform.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 25,
    categorySlug: 'mikrofone',
    specs: [
      { label: 'Typ', value: 'Lapel Funk' },
      { label: 'Anwendung', value: 'Interviews/TV' },
      { label: 'Größe', value: 'Kompakt' },
    ],
  },
  {
    id: 'mic-dynamic',
    name: 'Dynamisches Kabelmikrofon',
    description: 'Robustes dynamisches Kabelmikrofon für Gesang und Instrumente. Legendäre Zuverlässigkeit.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 15,
    categorySlug: 'mikrofone',
    specs: [
      { label: 'Typ', value: 'Dynamisch Kabel' },
      { label: 'Anwendung', value: 'Gesang/Instrumente' },
      { label: 'Robustheit', value: 'Sehr hoch' },
    ],
  },
  {
    id: 'mic-condenser',
    name: 'Kondensator-Mikrofon',
    description: 'Hochwertiges Kondensator-Mikrofon für Studio-Qualität. Perfekt für Aufnahmen und akustische Musik.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'mikrofone',
    specs: [
      { label: 'Typ', value: 'Kondensator' },
      { label: 'Anwendung', value: 'Studio/Aufnahmen' },
      { label: 'Stromversorgung', value: 'Phantom Power' },
    ],
  },

  // Nebelmaschinen
  {
    id: 'fog-machine-compact',
    name: 'Nebelmaschine Compact',
    description: 'Kompakte Nebelmaschine für kleine bis mittlere Räume. Schnelle Aufwärmzeit und gleichmäßiger Nebelausstoß.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 25,
    categorySlug: 'nebelmaschinen',
    specs: [
      { label: 'Leistung', value: '1000W' },
      { label: 'Ausstoß', value: '5000 ft³/min' },
      { label: 'Aufwärmzeit', value: '3-5 min' },
    ],
  },
  {
    id: 'fog-machine-pro',
    name: 'Nebelmaschine Professional',
    description: 'Professionelle Nebelmaschine für große Events. Starker Nebelausstoß und DMX-Steuerung.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 45,
    categorySlug: 'nebelmaschinen',
    specs: [
      { label: 'Leistung', value: '1500W' },
      { label: 'Ausstoß', value: '10000 ft³/min' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'haze-machine',
    name: 'Haze-Maschine',
    description: 'Dezenter Haze für subtile Lichteffekte. Erzeugt gleichmäßigen Dunst ohne starke Wolken.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'nebelmaschinen',
    specs: [
      { label: 'Typ', value: 'Haze' },
      { label: 'Ausstoß', value: 'Kontinuierlich' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'fog-machine-outdoor',
    name: 'Outdoor Nebelmaschine',
    description: 'Robuste Nebelmaschine für Außenveranstaltungen. Wetterfest und leistungsstark.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 55,
    categorySlug: 'nebelmaschinen',
    specs: [
      { label: 'Leistung', value: '2000W' },
      { label: 'Typ', value: 'Outdoor' },
      { label: 'Ausstoß', value: '15000 ft³/min' },
    ],
  },
  {
    id: 'fog-juice',
    name: 'Nebelfluid (5L)',
    description: 'Hochwertiges Nebelfluid für professionelle Nebeleffekte. Umweltfreundlich und geruchsneutral.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 20,
    categorySlug: 'nebelmaschinen',
    specs: [
      { label: 'Inhalt', value: '5 Liter' },
      { label: 'Typ', value: 'Premium Fluid' },
      { label: 'Umwelt', value: 'Freundlich' },
    ],
  },

  // Beamer
  {
    id: 'projector-fullhd',
    name: 'Beamer Full HD',
    description: 'Hochauflösender Full HD Beamer für Präsentationen und Videowände. Helle Lichtstärke für helle Räume.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'beamer',
    specs: [
      { label: 'Auflösung', value: 'Full HD (1920x1080)' },
      { label: 'Helligkeit', value: '3500 Lumen' },
      { label: 'Anschlüsse', value: 'HDMI, VGA, USB' },
    ],
  },
  {
    id: 'projector-4k',
    name: 'Beamer 4K UHD',
    description: 'Ultra HD 4K Beamer für höchste Bildqualität. Ideal für Premium-Präsentationen und Videowände.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 150,
    categorySlug: 'beamer',
    specs: [
      { label: 'Auflösung', value: '4K UHD (3840x2160)' },
      { label: 'Helligkeit', value: '5000 Lumen' },
      { label: 'HDR', value: 'Ja' },
    ],
  },
  {
    id: 'projector-short-throw',
    name: 'Short-Throw Beamer',
    description: 'Kurzdistanz-Projektor für kleine Räume. Großes Bild aus kurzer Entfernung.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 120,
    categorySlug: 'beamer',
    specs: [
      { label: 'Auflösung', value: 'Full HD' },
      { label: 'Helligkeit', value: '3000 Lumen' },
      { label: 'Typ', value: 'Short Throw' },
    ],
  },
  {
    id: 'projector-portable',
    name: 'Portabler Mini-Beamer',
    description: 'Leichtgewichtiger, tragbarer Beamer für spontane Präsentationen. Kompakt und leistungsstark.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 60,
    categorySlug: 'beamer',
    specs: [
      { label: 'Auflösung', value: 'HD (1280x800)' },
      { label: 'Helligkeit', value: '2500 Lumen' },
      { label: 'Gewicht', value: '2.5kg' },
    ],
  },
  {
    id: 'projector-screen',
    name: 'Leinwand 3x2m',
    description: 'Professionelle Projektionsleinwand für optimale Bilddarstellung. Elektrisch verfahrbar.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'beamer',
    specs: [
      { label: 'Größe', value: '3x2 Meter' },
      { label: 'Typ', value: 'Elektrisch' },
      { label: 'Format', value: '16:9' },
    ],
  },

  // Stromerzeuger
  {
    id: 'generator-2kw',
    name: 'Stromerzeuger 2kW',
    description: 'Kompakter 2kW Stromerzeuger für kleine Veranstaltungen. Leicht und transportabel.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 60,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '2kW' },
      { label: 'Kraftstoff', value: 'Benzin' },
      { label: 'Gewicht', value: '25kg' },
    ],
  },
  {
    id: 'generator-3-5kw',
    name: 'Stromerzeuger 3,5kW',
    description: 'Mittlerer Stromerzeuger für mittlere Events. Ausgewogenes Verhältnis aus Leistung und Mobilität.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 80,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '3,5kW' },
      { label: 'Kraftstoff', value: 'Benzin' },
      { label: 'Gewicht', value: '45kg' },
    ],
  },
  {
    id: 'generator-6-5kw',
    name: 'Stromerzeuger 6,5kW',
    description: 'Leistungsstarker 6,5kW Generator für große Veranstaltungen. Dieselbetrieb für längere Laufzeiten.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 120,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '6,5kW' },
      { label: 'Kraftstoff', value: 'Diesel' },
      { label: 'Laufzeit', value: '8-10h' },
    ],
  },
  {
    id: 'generator-silent',
    name: 'Stromerzeuger Silent',
    description: 'Leiser Stromerzeuger für Veranstaltungen in ruhigen Umgebungen. Geringe Geräuschemission.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 100,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '3kW' },
      { label: 'Lautstärke', value: '< 60dB' },
      { label: 'Kraftstoff', value: 'Benzin' },
    ],
  },
  {
    id: 'power-distribution',
    name: 'Stromverteiler 8x CEE',
    description: 'Professioneller Stromverteiler mit 8 CEE-Steckdosen. Sicher und übersichtlich für mehrere Geräte.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 30,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Anschlüsse', value: '8x CEE' },
      { label: 'Sicherung', value: 'Schutzschalter' },
      { label: 'Kabel', value: '20m inkl.' },
    ],
  },

  // Lichtsteuerung
  {
    id: 'dmx-controller-basic',
    name: 'DMX Controller Basic',
    description: 'Einfacher DMX-Controller für grundlegende Lichtsteuerung. Perfekt für Einsteiger.',
    images: ['/images/quickq10_1-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'lichtsteuerung',
    specs: [
      { label: 'Kanäle', value: '512 DMX' },
      { label: 'Fader', value: '12' },
      { label: 'Typ', value: 'Hardware' },
    ],
  },
  {
    id: 'dmx-controller-pro',
    name: 'DMX Controller Professional',
    description: 'Professioneller DMX-Controller mit Touchscreen und erweiterten Features für komplexe Lichtshows.',
    images: ['/images/quickq10_1-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'lichtsteuerung',
    specs: [
      { label: 'Kanäle', value: '2048 DMX' },
      { label: 'Display', value: 'Touchscreen' },
      { label: 'Shows', value: 'Pre-programmed' },
    ],
  },
  {
    id: 'dmx-interface',
    name: 'DMX Interface USB',
    description: 'DMX-Interface für PC-Steuerung. Steuern Sie Ihre Lichter mit professioneller Software.',
    images: ['/images/quickq10_1-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'lichtsteuerung',
    specs: [
      { label: 'Anschluss', value: 'USB' },
      { label: 'Kanäle', value: '512 DMX' },
      { label: 'Software', value: 'Inklusive' },
    ],
  },
  {
    id: 'light-software',
    name: 'Lichtsteuerungs-Software',
    description: 'Professionelle Software für komplexe Lichtprogrammierung. Zeitbasierte Shows und Live-Steuerung.',
    images: ['/images/quickq10_1-1920w.webp'],
    pricePerUnit: 25,
    categorySlug: 'lichtsteuerung',
    specs: [
      { label: 'Plattform', value: 'Windows/Mac' },
      { label: 'Features', value: 'Timecode, 3D-Visualizer' },
      { label: 'Lizenz', value: 'Profi-Version' },
    ],
  },
  {
    id: 'dmx-splitter',
    name: 'DMX Splitter 4-Wege',
    description: 'DMX-Splitter für mehrere DMX-Leitungen. Verlängert Reichweite und verteilt Signal.',
    images: ['/images/quickq10_1-1920w.webp'],
    pricePerUnit: 35,
    categorySlug: 'lichtsteuerung',
    specs: [
      { label: 'Ausgänge', value: '4x DMX' },
      { label: 'Isolation', value: 'Galvanisch' },
      { label: 'Reichweite', value: '500m' },
    ],
  },

  // Traversen
  {
    id: 'truss-triangle',
    name: 'Traverse Dreieck 3m',
    description: 'Stabile Dreieck-Traverse für sicheren Aufbau von Licht und Ton. TÜV-geprüft.',
    images: ['/images/stative.jpg'],
    pricePerUnit: 25,
    categorySlug: 'traversen',
    specs: [
      { label: 'Länge', value: '3 Meter' },
      { label: 'Form', value: 'Dreieck' },
      { label: 'Last', value: 'bis 500kg' },
    ],
  },
  {
    id: 'truss-square',
    name: 'Traverse Quadrat 3m',
    description: 'Quadratische Traverse für maximale Stabilität. Ideal für große Lasten und komplexe Aufbauten.',
    images: ['/images/stative.jpg'],
    pricePerUnit: 30,
    categorySlug: 'traversen',
    specs: [
      { label: 'Länge', value: '3 Meter' },
      { label: 'Form', value: 'Quadrat' },
      { label: 'Last', value: 'bis 800kg' },
    ],
  },
  {
    id: 'truss-tower',
    name: 'Traversen-Turm',
    description: 'Vorgefertigter Traversen-Turm für schnellen Aufbau. Perfekt für Sidefills und Backline.',
    images: ['/images/stative.jpg'],
    pricePerUnit: 80,
    categorySlug: 'traversen',
    specs: [
      { label: 'Höhe', value: '4 Meter' },
      { label: 'Basis', value: '2x2 Meter' },
      { label: 'Last', value: 'bis 300kg' },
    ],
  },
  {
    id: 'truss-adapter',
    name: 'Traversen-Verbinder',
    description: 'Verschiedene Adapter und Verbinder für flexiblen Traversen-Aufbau. Winkel, T-Stücke, etc.',
    images: ['/images/stative.jpg'],
    pricePerUnit: 5,
    categorySlug: 'traversen',
    specs: [
      { label: 'Typen', value: 'Winkel, T, Kreuz' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Passend für', value: 'Alle Traversen' },
    ],
  },
  {
    id: 'truss-base',
    name: 'Traversen-Fuß',
    description: 'Stabile Bodenplatten für sichere Traversen-Befestigung. Verstellbare Höhe.',
    images: ['/images/stative.jpg'],
    pricePerUnit: 15,
    categorySlug: 'traversen',
    specs: [
      { label: 'Typ', value: 'Bodenplatte' },
      { label: 'Höhenausgleich', value: 'Verstellbar' },
      { label: 'Material', value: 'Stahl' },
    ],
  },

  // Bühnenpodeste
  {
    id: 'stage-30cm',
    name: 'Bühnenpodest 30cm',
    description: 'Niedriges Podest für kleine Bühnen und Präsentationen. Modular erweiterbar.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 20,
    categorySlug: 'buehlenpodeste',
    specs: [
      { label: 'Höhe', value: '30cm' },
      { label: 'Größe', value: '1x1 Meter' },
      { label: 'Belastung', value: 'bis 500kg/m²' },
    ],
  },
  {
    id: 'stage-60cm',
    name: 'Bühnenpodest 60cm',
    description: 'Mittelhohes Podest für Bands und Performances. Standard-Höhe für die meisten Events.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 25,
    categorySlug: 'buehlenpodeste',
    specs: [
      { label: 'Höhe', value: '60cm' },
      { label: 'Größe', value: '1x1 Meter' },
      { label: 'Belastung', value: 'bis 500kg/m²' },
    ],
  },
  {
    id: 'stage-100cm',
    name: 'Bühnenpodest 100cm',
    description: 'Hohes Podest für große Bühnen und Konzerte. Maximale Sichtbarkeit für Performances.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 30,
    categorySlug: 'buehlenpodeste',
    specs: [
      { label: 'Höhe', value: '100cm' },
      { label: 'Größe', value: '1x1 Meter' },
      { label: 'Belastung', value: 'bis 500kg/m²' },
    ],
  },
  {
    id: 'stage-trapez',
    name: 'Trapez-Podest',
    description: 'Trapezförmiges Podest für runde Bühnenformen. Flexible Gestaltung möglich.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 22,
    categorySlug: 'buehlenpodeste',
    specs: [
      { label: 'Höhe', value: '60cm' },
      { label: 'Form', value: 'Trapez' },
      { label: 'Belastung', value: 'bis 500kg/m²' },
    ],
  },
  {
    id: 'stage-ramp',
    name: 'Podest-Rampe',
    description: 'Zugangsrampe für barrierefreien Bühnenzugang. Sicher und rutschfest.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 35,
    categorySlug: 'buehlenpodeste',
    specs: [
      { label: 'Länge', value: '2 Meter' },
      { label: 'Breite', value: '1 Meter' },
      { label: 'Neigung', value: '1:12' },
    ],
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter(product => product.categorySlug === categorySlug);
}

export function getProductById(id: string): Product | undefined {
  return products.find(product => product.id === id);
}
