export interface Product {
  id: string;
  name: string;
  description: string;
  images: string[];
  pricePerUnit: number;
  pricePerPair?: number;
  categorySlug: string;
  features?: string[];
  specs?: { label: string; value: string }[];
}

export const products: Product[] = [
  // Party-Sets Ton & Licht
  {
    id: 'party-set-small',
    name: 'Party-Set SMALL',
    description: 'Enthält PA-System, Mischpult, Mikrofone und Basis-Beleuchtung.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 200,
    categorySlug: 'party-sets-ton-licht',
    features: ['PA bis 50 Personen', '16-Kanal Mischpult', '2 Funkmikrofone', 'Basis-Lichtset'],
  },
  {
    id: 'party-set-medium',
    name: 'Party-Set MEDIUM',
    description: 'Erweiterte Ausstattung mit besserem Sound und professioneller Beleuchtung.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 300,
    categorySlug: 'party-sets-ton-licht',
    features: ['PA bis 100 Personen', '24-Kanal Mischpult', '4 Funkmikrofone', 'LED-Spots + Moving Heads'],
  },
  {
    id: 'party-set-white',
    name: 'Party-Set WHITE',
    description: 'Speziell für elegante Veranstaltungen. Dezente Beleuchtung und klarer Sound für einen unvergesslichen Anlass.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 350,
    categorySlug: 'party-sets-ton-licht',
    features: ['PA bis 120 Personen', '24-Kanal Mischpult', '4 Funkmikrofone', 'Elegante weiße Beleuchtung'],
  },
  {
    id: 'party-set-large',
    name: 'Party-Set LARGE',
    description: 'Premium-Ausstattung mit professionellem System und umfangreicher Lichttechnik.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 450,
    categorySlug: 'party-sets-ton-licht',
    features: ['PA bis 150 Personen', '32-Kanal Digital Mixer', '6 Funkmikrofone', 'Vollständige Lichtshow'],
  },
  {
    id: 'party-set-xlarge',
    name: 'Party-Set X-LARGE',
    description: 'Maximale Ausstattung für große Events. Professionelles Line Array System mit umfangreicher Lichttechnik.',
    images: ['/images/profx3-1920w.webp'],
    pricePerUnit: 650,
    categorySlug: 'party-sets-ton-licht',
    features: ['PA bis 250 Personen', '32-Kanal Digital Mixer', '8 Funkmikrofone', 'Vollständige Lichtshow mit Moving Heads'],
  },

  // PA-Anlagen / Lautsprecher
  {
    id: 'akku-lautsprecher-compact',
    name: 'Akku Lautsprecher Compact',
    description: 'Kompakter Akku-Lautsprecher. Mobil und flexibel einsetzbar.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Typ', value: 'Akku-Lautsprecher' },
      { label: 'Personen', value: 'bis 30' },
      { label: 'Laufzeit', value: 'bis 8h' },
    ],
  },
  {
    id: 'akku-lautsprecher-maxi',
    name: 'Akku Lautsprecher Maxi',
    description: 'Großer Akku-Lautsprecher mit mehr Leistung. Lange Laufzeit.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Typ', value: 'Akku-Lautsprecher' },
      { label: 'Personen', value: 'bis 80' },
      { label: 'Laufzeit', value: 'bis 12h' },
    ],
  },
  {
    id: 'aktivlautsprecher-bluetooth',
    name: 'Aktivlautsprecher Bluetooth',
    description: 'Professioneller Aktivlautsprecher mit Bluetooth-Funktion.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 60,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Typ', value: 'Aktiv Bluetooth' },
      { label: 'Personen', value: 'bis 50' },
      { label: 'Anschlüsse', value: 'Bluetooth, XLR, Klinke' },
    ],
  },
  {
    id: 'sub-sat-set-bluetooth',
    name: 'Sub-Sat Set Bluetooth',
    description: 'Kompaktes Subwoofer-Satelliten-Set mit Bluetooth. Kraftvoller Bass und klare Höhen.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 100,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Typ', value: 'Sub-Sat Set' },
      { label: 'Personen', value: 'bis 60' },
      { label: 'Anschlüsse', value: 'Bluetooth, XLR' },
    ],
  },
  {
    id: 'pa-saeule-bluetooth',
    name: 'PA Säule Bluetooth',
    description: 'Professionelle PA-Säule mit Bluetooth-Konnektivität.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 90,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Typ', value: 'PA Säule' },
      { label: 'Personen', value: 'bis 100' },
      { label: 'Anschlüsse', value: 'Bluetooth, XLR, Klinke' },
    ],
  },
  {
    id: 'pa-set-small',
    name: 'PA Set SMALL',
    description: 'Kompaktes PA-Set mit professionellem Sound in kompakter Form.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 120,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '500W RMS' },
      { label: 'Personen', value: 'bis 100' },
      { label: 'Typ', value: 'Aktiv' },
    ],
  },
  {
    id: 'pa-set-medium',
    name: 'PA Set MEDIUM',
    description: 'Mittleres PA-Set mit kraftvollem Sound.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 180,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '1000W RMS' },
      { label: 'Personen', value: 'bis 200' },
      { label: 'Typ', value: 'Aktiv' },
    ],
  },
  {
    id: 'pa-set-large',
    name: 'PA Set LARGE',
    description: 'Großes PA-Set mit professionellem Sound und Subwoofer.',
    images: ['/images/audiozenit-1920w.webp'],
    pricePerUnit: 280,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '2000W RMS' },
      { label: 'Personen', value: 'bis 300' },
      { label: 'Typ', value: 'Aktiv + Sub' },
    ],
  },
  {
    id: 'pa-set-xlarge',
    name: 'PA Set X-LARGE',
    description: 'Sehr großes PA-Set mit maximaler Leistung und Klangqualität.',
    images: ['/images/palive2-1920w.webp'],
    pricePerUnit: 450,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '4000W RMS' },
      { label: 'Personen', value: 'bis 500' },
      { label: 'Typ', value: 'Aktiv + Sub' },
    ],
  },
  {
    id: 'pa-set-premium',
    name: 'PA Set PREMIUM',
    description: 'Premium PA-Set mit höchster Klangqualität. Für anspruchsvolle Veranstaltungen und Events.',
    images: ['/images/palive2-1920w.webp'],
    pricePerUnit: 600,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '6000W RMS' },
      { label: 'Personen', value: 'bis 800' },
      { label: 'Typ', value: 'Premium Line Array' },
    ],
  },
  {
    id: 'pa-set-outdoor',
    name: 'PA Set OUTDOOR',
    description: 'Robustes PA-Set speziell für Outdoor-Veranstaltungen. Wetterfest und leistungsstark.',
    images: ['/images/palive2-1920w.webp'],
    pricePerUnit: 400,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Leistung', value: '3000W RMS' },
      { label: 'Personen', value: 'bis 400' },
      { label: 'Typ', value: 'Outdoor-geeignet' },
    ],
  },
  {
    id: 'profi-pa-line-array-event-26a',
    name: 'Profi PA / Line-Array Event 26A',
    description: 'Professionelles Line-Array System für große Events. Höchste Klangqualität und maximale Reichweite.',
    images: ['/images/palive2-1920w.webp'],
    pricePerUnit: 800,
    categorySlug: 'pa-anlagen',
    specs: [
      { label: 'Typ', value: 'Line-Array System' },
      { label: 'Personen', value: 'bis 1000+' },
      { label: 'Leistung', value: '8000W+ RMS' },
    ],
  },

  // Mischpulte & Mikrofone
  {
    id: 'allen-heath-sq5',
    name: 'Allen & Heath SQ-5',
    description: 'Professionelles Digital-Mischpult mit Touchscreen und umfangreichen Features.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 250,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Allen & Heath' },
      { label: 'Typ', value: 'Digital Mixer' },
      { label: 'Kanäle', value: '32' },
    ],
  },
  {
    id: 'allen-heath-ar2412',
    name: 'Allen & Heath AR2412',
    description: 'Professionelles Analog-Mischpult mit 24 Eingangskanälen.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 150,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Allen & Heath' },
      { label: 'Typ', value: 'Analog Mixer' },
      { label: 'Kanäle', value: '24' },
    ],
  },
  {
    id: 'yamaha-dm3',
    name: 'Yamaha DM-3',
    description: 'Kompaktes Digital-Mischpult mit moderner Bedienoberfläche.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 200,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Yamaha' },
      { label: 'Typ', value: 'Digital Mixer' },
      { label: 'Kanäle', value: '16' },
    ],
  },
  {
    id: 'yamaha-tio-1608d',
    name: 'Yamaha TIO-1608D',
    description: 'Stagebox für digitale Mischpulte mit 16 Eingängen.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 180,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Yamaha' },
      { label: 'Typ', value: 'Stagebox' },
      { label: 'Eingänge', value: '16' },
    ],
  },
  {
    id: 'dynacord-cms-1600-3',
    name: 'DYNACORD CMS 1600-3',
    description: 'Professionelles Digital-Mischpult mit umfangreichen Features.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 300,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'DYNACORD' },
      { label: 'Typ', value: 'Digital Mixer' },
      { label: 'Kanäle', value: '16' },
    ],
  },
  {
    id: 'pioneer-djm-900-nexus',
    name: 'Pioneer DJM-900 Nexus',
    description: 'Professioneller DJ-Mixer mit erweiterten Mixing-Features und Effekten.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 120,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Pioneer' },
      { label: 'Typ', value: 'DJ Mixer' },
      { label: 'Kanäle', value: '4' },
    ],
  },
  {
    id: 'mackie-analog-mixer',
    name: 'Analoge MACKIE Mischpulte',
    description: 'Zuverlässige analoge Mischpulte von MACKIE in verschiedenen Größen.',
    images: ['/images/chorkonzert-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'MACKIE' },
      { label: 'Typ', value: 'Analog Mixer' },
      { label: 'Varianten', value: '16/24/32 Kanäle' },
    ],
  },
  {
    id: 'shure-mikrofon-set-sm58-sm57',
    name: 'Shure Mikrofon Set SM58 / SM57',
    description: 'Professionelles Mikrofon-Set mit Shure SM58 für Gesang und SM57 für Instrumente.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Shure' },
      { label: 'Typ', value: 'Dynamisch Kabel' },
      { label: 'Set', value: 'SM58 + SM57' },
    ],
  },
  {
    id: 'mikrofon-set-drums',
    name: 'Mikrofon Set für Drums / Schlagzeug',
    description: 'Komplettes Mikrofon-Set für professionelle Schlagzeug-Aufnahme.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 100,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Typ', value: 'Drum-Mikrofon Set' },
      { label: 'Anwendung', value: 'Schlagzeug' },
      { label: 'Komponenten', value: 'Kick, Snare, Toms, Overhead' },
    ],
  },
  {
    id: 'funkmikrofon-sprache-moderation',
    name: 'Funkmikrofon für Sprache / Moderation',
    description: 'Professionelles Funkmikrofon speziell für Sprache und Moderation.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 35,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Typ', value: 'Funkmikrofon' },
      { label: 'Anwendung', value: 'Sprache/Moderation' },
      { label: 'Frequenz', value: 'UHF' },
    ],
  },
  {
    id: 'profi-funkmikrofon-shure-slxd2',
    name: 'Profi Funkmikrofon Shure SLXD2',
    description: 'Professionelles Funkmikrofon von Shure für höchste Ansprüche.',
    images: ['/images/slxd4e86-1920w.webp'],
    pricePerUnit: 60,
    categorySlug: 'mischpulte-mikrofone',
    specs: [
      { label: 'Hersteller', value: 'Shure' },
      { label: 'Typ', value: 'Funkmikrofon' },
      { label: 'Modell', value: 'SLXD2' },
    ],
  },

  // Statische Scheinwerfer / LED Spots
  {
    id: 'akku-spot-indoor-rgb',
    name: 'Akku Spot Indoor RGB',
    description: 'Kompakter Akku-Spot mit RGB-Farbspektrum für den Innenbereich. Mobil und flexibel einsetzbar.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 20,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'Akku Spot' },
      { label: 'Farben', value: 'RGB' },
      { label: 'Anwendung', value: 'Indoor' },
    ],
  },
  {
    id: 'akku-spot-outdoor-rgbw-ip65',
    name: 'Akku Spot Outdoor RGBW, IP65',
    description: 'Wetterfester Akku-Spot mit RGBW-Farbspektrum für den Außenbereich. IP65 geschützt.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 35,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'Akku Spot' },
      { label: 'Farben', value: 'RGBW' },
      { label: 'Schutz', value: 'IP65' },
    ],
  },
  {
    id: 'led-outdoor-fluter-ip65',
    name: 'LED Outdoor Fluter, IP65',
    description: 'Professioneller LED-Fluter für Außenbeleuchtung. Wetterfest mit IP65 Schutz.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'LED Fluter' },
      { label: 'Schutz', value: 'IP65' },
      { label: 'Anwendung', value: 'Outdoor' },
    ],
  },
  {
    id: 'led-verfolgerspot-follow-spot',
    name: 'LED Verfolgerspot Follow Spot',
    description: 'Professioneller LED-Verfolgerspot für Bühnenbeleuchtung. Präzise Steuerung und hohe Lichtleistung.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'Follow Spot' },
      { label: 'Technologie', value: 'LED' },
      { label: 'Anwendung', value: 'Bühne' },
    ],
  },
  {
    id: 'led-pll-panel-power-strobe',
    name: 'LED PLL Panel / Power Strobe',
    description: 'Kraftvolles LED-Panel mit Stroboskop-Funktion. Intensive Lichteffekte für Events.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'LED Panel' },
      { label: 'Features', value: 'Stroboskop' },
      { label: 'Leistung', value: 'High Power' },
    ],
  },
  {
    id: 'party-lichtset-kompakt',
    name: 'Party Lichtset kompakt',
    description: 'Kompaktes Party-Lichtset mit verschiedenen LED-Effekten. Alles-in-einem Lösung.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 60,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'Lichtset' },
      { label: 'Größe', value: 'Kompakt' },
      { label: 'Anwendung', value: 'Party' },
    ],
  },
  {
    id: 'led-pro-lichtbar-rgb',
    name: 'LED Pro Lichtbar RGB',
    description: 'Professionelle LED-Lichtbar mit RGB-Farbspektrum. Für anspruchsvolle Beleuchtung.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 45,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'LED Lichtbar' },
      { label: 'Farben', value: 'RGB' },
      { label: 'Klasse', value: 'Pro' },
    ],
  },
  {
    id: 'led-effekt-bar-mit-scannern',
    name: 'LED Effekt Bar mit Scannern',
    description: 'LED-Effektbar mit integrierten Scannern für dynamische Lichtshows.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 70,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'LED Effekt Bar' },
      { label: 'Features', value: 'Scannern' },
      { label: 'Anwendung', value: 'Lichtshow' },
    ],
  },
  {
    id: 'high-power-led-effekt-bar-mit-laser',
    name: 'High-Power LED Effekt Bar mit Laser',
    description: 'Hochleistungs LED-Effektbar mit integriertem Laser. Maximale Lichtintensität für große Events.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 120,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'LED Effekt Bar' },
      { label: 'Features', value: 'Laser' },
      { label: 'Leistung', value: 'High Power' },
    ],
  },
  {
    id: 'led-lichterketten-innen-aussen',
    name: 'LED Lichterketten für innen und außen',
    description: 'Flexible LED-Lichterketten für Innen- und Außenbereich. Dekorative Beleuchtung.',
    images: ['/images/kls120_1-1920w.webp'],
    pricePerUnit: 25,
    categorySlug: 'statische-scheinwerfer-led-spots',
    specs: [
      { label: 'Typ', value: 'LED Lichterkette' },
      { label: 'Anwendung', value: 'Indoor & Outdoor' },
      { label: 'Länge', value: 'Variabel' },
    ],
  },

  // Moving Heads / Lichteffekte
  {
    id: 'led-derby-effekt-mit-strobe',
    name: 'LED Derby Effekt mit Strobe',
    description: 'Dynamischer LED-Derby-Effekt mit integriertem Stroboskop. Für intensive Lichtshows.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'LED Derby' },
      { label: 'Features', value: 'Stroboskop' },
      { label: 'Anwendung', value: 'Lichtshow' },
    ],
  },
  {
    id: 'led-triple-flower',
    name: 'LED Triple Flower',
    description: 'LED-Effektgerät mit drei rotierenden Blüten. Atmosphärische Beleuchtungseffekte.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 35,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'LED Flower' },
      { label: 'Anzahl', value: '3 Blüten' },
      { label: 'Effekt', value: 'Rotierend' },
    ],
  },
  {
    id: 'mirror-ball-saturn-led-effekt',
    name: 'Mirror Ball / Saturn LED Effekt',
    description: 'Spiegelkugel mit LED-Saturn-Effekt. Klassischer Disco-Effekt mit moderner LED-Technologie.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 30,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Mirror Ball' },
      { label: 'Features', value: 'LED Saturn' },
      { label: 'Anwendung', value: 'Disco/Party' },
    ],
  },
  {
    id: 'led-moving-head-spot-100w',
    name: 'LED Moving Head Spot 100W',
    description: 'Professioneller LED Moving Head Spot mit 100W Leistung. Präzise Bewegungen und vielfältige Effekte.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Moving Head Spot' },
      { label: 'Leistung', value: '100W' },
      { label: 'Technologie', value: 'LED' },
    ],
  },
  {
    id: 'led-moving-head-beam-200w',
    name: 'LED Moving Head Beam 200W',
    description: 'Scharf gebündelter LED Moving Head Beam mit 200W. Dramatische Lichtstrahlen für große Events.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 70,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Moving Head Beam' },
      { label: 'Leistung', value: '200W' },
      { label: 'Beam-Winkel', value: 'Narrow' },
    ],
  },
  {
    id: 'led-moving-head-wash-7x40w',
    name: 'LED Moving Head WASH 7 x 40W',
    description: 'Weitwinkliger LED Moving Head Wash mit 7 x 40W. Gleichmäßige Ausleuchtung mit Bewegungsmöglichkeit.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Moving Head Wash' },
      { label: 'Leistung', value: '7 x 40W' },
      { label: 'Beam-Winkel', value: 'Weitwinklig' },
    ],
  },
  {
    id: 'jb-spyder-show-pattern-laser',
    name: 'JB Spyder Show- / Pattern Laser',
    description: 'Professioneller Show-Laser mit Pattern-Funktion. Atemberaubende Laser-Effekte für Events.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 150,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Show Laser' },
      { label: 'Features', value: 'Pattern' },
      { label: 'Hersteller', value: 'JB Spyder' },
    ],
  },
  {
    id: '2000mw-diodenlaser-showlaser',
    name: '2.000 mW Diodenlaser Showlaser',
    description: 'Hochleistungs-Diodenlaser mit 2000mW für professionelle Laser-Shows. Intensive Laser-Effekte.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 200,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Diodenlaser' },
      { label: 'Leistung', value: '2000 mW' },
      { label: 'Anwendung', value: 'Show Laser' },
    ],
  },
  {
    id: 'led-wasser-projektionseffekt',
    name: 'LED Wasser Projektionseffekt',
    description: 'LED-Projektionseffekt für Wasser-Oberflächen. Atmosphärische Beleuchtung für Events.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 60,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Wasser Projektion' },
      { label: 'Technologie', value: 'LED' },
      { label: 'Anwendung', value: 'Wasser-Effekte' },
    ],
  },
  {
    id: '50cm-spiegelkugel-set',
    name: '50cm Spiegelkugel SET',
    description: 'Komplettes Set mit 50cm Spiegelkugel und Motor. Klassischer Disco-Effekt.',
    images: ['/images/sk3-1920w.webp'],
    pricePerUnit: 45,
    categorySlug: 'moving-heads',
    specs: [
      { label: 'Typ', value: 'Spiegelkugel Set' },
      { label: 'Größe', value: '50cm' },
      { label: 'Inhalt', value: 'Kugel + Motor' },
    ],
  },


  // Nebelmaschinen & Bühneneffekte
  {
    id: 'party-nebelmaschine-800w',
    name: 'Party Nebelmaschine 800W',
    description: 'Kompakte Party-Nebelmaschine mit 800W Leistung. Ideal für kleine bis mittlere Veranstaltungen.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 25,
    categorySlug: 'nebelmaschinen-buehneneffekte',
    specs: [
      { label: 'Leistung', value: '800W' },
      { label: 'Typ', value: 'Party Nebelmaschine' },
      { label: 'Anwendung', value: 'Kleine bis mittlere Events' },
    ],
  },
  {
    id: 'nebelmaschine-1500w',
    name: 'Nebelmaschine 1.500W',
    description: 'Professionelle Nebelmaschine mit 1500W Leistung. Starker Nebelausstoß für große Events.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 45,
    categorySlug: 'nebelmaschinen-buehneneffekte',
    specs: [
      { label: 'Leistung', value: '1500W' },
      { label: 'Typ', value: 'Nebelmaschine' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'vertikal-nebelmaschine-spray-fogger',
    name: 'Vertikal Nebelmaschine / Spray Fogger',
    description: 'Vertikale Nebelmaschine für spezielle Effekte. Spray Fogger für eindrucksvolle Nebelwände.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 55,
    categorySlug: 'nebelmaschinen-buehneneffekte',
    specs: [
      { label: 'Typ', value: 'Vertikal / Spray Fogger' },
      { label: 'Richtung', value: 'Vertikal' },
      { label: 'Anwendung', value: 'Spezialeffekte' },
    ],
  },
  {
    id: 'hazer',
    name: 'Hazer',
    description: 'Dezenter Haze für subtile Lichteffekte. Erzeugt gleichmäßigen Dunst ohne starke Wolken.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 50,
    categorySlug: 'nebelmaschinen-buehneneffekte',
    specs: [
      { label: 'Typ', value: 'Hazer' },
      { label: 'Ausstoß', value: 'Kontinuierlich' },
      { label: 'DMX', value: 'Ja' },
    ],
  },
  {
    id: 'bodennebelmaschine',
    name: 'Bodennebelmaschine',
    description: 'Spezielle Nebelmaschine für Bodeneffekte. Erzeugt Nebel, der am Boden bleibt.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 40,
    categorySlug: 'nebelmaschinen-buehneneffekte',
    specs: [
      { label: 'Typ', value: 'Bodennebelmaschine' },
      { label: 'Effekt', value: 'Bodennebel' },
      { label: 'Anwendung', value: 'Bühnen-Effekte' },
    ],
  },
  {
    id: 'kaltfunkenmaschine-cold-spark',
    name: 'Kaltfunkenmaschine "Cold Spark"',
    description: 'Kaltfunkenmaschine für spektakuläre Funken-Effekte. Sicher und eindrucksvoll.',
    images: ['/images/z1200_1-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'nebelmaschinen-buehneneffekte',
    specs: [
      { label: 'Typ', value: 'Cold Spark' },
      { label: 'Effekt', value: 'Kaltfunken' },
      { label: 'Sicherheit', value: 'Kalt, sicher' },
    ],
  },

  // Medien & Konferenztechnik
  {
    id: 'lcd-dlp-beamer',
    name: 'LCD DLP Beamer',
    description: 'Professioneller LCD DLP Beamer für Präsentationen und Videowände.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Technologie', value: 'LCD DLP' },
      { label: 'Auflösung', value: 'Full HD' },
      { label: 'Anschlüsse', value: 'HDMI, VGA, USB' },
    ],
  },
  {
    id: 'laser-dlp-beamer',
    name: 'Laser DLP Beamer',
    description: 'Laser DLP Beamer mit langer Lebensdauer und konstanter Helligkeit.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 150,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Technologie', value: 'Laser DLP' },
      { label: 'Auflösung', value: 'Full HD' },
      { label: 'Vorteil', value: 'Lange Lebensdauer' },
    ],
  },
  {
    id: 'laser-dlp-beamer-pro',
    name: 'Laser DLP Beamer Pro',
    description: 'Professioneller Laser DLP Beamer mit erweiterten Features für anspruchsvolle Präsentationen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 200,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Technologie', value: 'Laser DLP Pro' },
      { label: 'Auflösung', value: 'Full HD / WUXGA' },
      { label: 'Helligkeit', value: 'Hoch' },
    ],
  },
  {
    id: '4k-laser-dlp-beamer',
    name: '4K Laser DLP Beamer',
    description: 'Ultra HD 4K Laser DLP Beamer für höchste Bildqualität. Ideal für Premium-Präsentationen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 300,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Technologie', value: '4K Laser DLP' },
      { label: 'Auflösung', value: '4K UHD (3840x2160)' },
      { label: 'HDR', value: 'Ja' },
    ],
  },
  {
    id: '4k-signature-display-65zoll',
    name: '4K Signature Display - 65 Zoll',
    description: 'Professionelles 4K Signature Display mit 65 Zoll. Höchste Bildqualität für Konferenzen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 250,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Größe', value: '65 Zoll' },
      { label: 'Auflösung', value: '4K UHD' },
      { label: 'Typ', value: 'Signature Display' },
    ],
  },
  {
    id: 'speech-100-konferenzsystem',
    name: 'Speech 100 - Konferenzsystem',
    description: 'Professionelles Konferenzsystem für klare Kommunikation in Meetings und Präsentationen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 120,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Typ', value: 'Konferenzsystem' },
      { label: 'Modell', value: 'Speech 100' },
      { label: 'Anwendung', value: 'Konferenzen' },
    ],
  },
  {
    id: 'leinwand-projection-screen-4m',
    name: 'Leinwand / Projection Screen 4m',
    description: 'Professionelle Projektionsleinwand 4 Meter Breite. Für große Präsentationen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 60,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Größe', value: '4 Meter' },
      { label: 'Typ', value: 'Projection Screen' },
      { label: 'Format', value: '16:9' },
    ],
  },
  {
    id: 'leinwand-projection-screen-3m',
    name: 'Leinwand / Projection Screen 3m',
    description: 'Professionelle Projektionsleinwand 3 Meter Breite. Standard-Größe für Präsentationen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 45,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Größe', value: '3 Meter' },
      { label: 'Typ', value: 'Projection Screen' },
      { label: 'Format', value: '16:9' },
    ],
  },
  {
    id: 'leinwand-projection-screen-2m',
    name: 'Leinwand / Projection Screen 2m',
    description: 'Kompakte Projektionsleinwand 2 Meter Breite. Ideal für kleine Räume.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 30,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Größe', value: '2 Meter' },
      { label: 'Typ', value: 'Projection Screen' },
      { label: 'Format', value: '16:9' },
    ],
  },
  {
    id: 'stativ-projektor-laptop',
    name: 'Stativ für Projektor / Laptop',
    description: 'Stabiles Stativ für Projektor oder Laptop. Höhenverstellbar und flexibel einsetzbar.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 20,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Typ', value: 'Stativ' },
      { label: 'Anwendung', value: 'Projektor / Laptop' },
      { label: 'Höhe', value: 'Verstellbar' },
    ],
  },
  {
    id: 'pro-av-mixer',
    name: 'Pro AV Mixer',
    description: 'Professioneller AV-Mixer für Audio- und Video-Signale. Ideal für Konferenzen und Events.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 100,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Typ', value: 'AV Mixer' },
      { label: 'Klasse', value: 'Pro' },
      { label: 'Signale', value: 'Audio & Video' },
    ],
  },
  {
    id: 'wireless-hdmi-funk-set',
    name: 'Wireless HDMI Funk-Set',
    description: 'Drahtloses HDMI-Funk-Set für kabellose Übertragung von Audio- und Video-Signalen.',
    images: ['/images/acer1-1920w.webp'],
    pricePerUnit: 80,
    categorySlug: 'medien-konferenztechnik',
    specs: [
      { label: 'Typ', value: 'Wireless HDMI' },
      { label: 'Reichweite', value: 'bis 30m' },
      { label: 'Auflösung', value: 'Full HD' },
    ],
  },

  // Stromerzeuger / Generatoren
  {
    id: 'inverter-stromerzeuger-2kw',
    name: 'Inverter Stromerzeuger 2 kW',
    description: 'Kompakter Inverter-Stromerzeuger mit 2 kW Leistung. Leise und sparsam für kleine Veranstaltungen.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 60,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '2 kW' },
      { label: 'Typ', value: 'Inverter' },
      { label: 'Vorteil', value: 'Leise & sparsam' },
    ],
  },
  {
    id: 'inverter-stromerzeuger-3-2kw',
    name: 'Inverter Stromerzeuger 3,2 kW',
    description: 'Mittlerer Inverter-Stromerzeuger mit 3,2 kW Leistung. Ideal für mittlere Events.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 80,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '3,2 kW' },
      { label: 'Typ', value: 'Inverter' },
      { label: 'Anwendung', value: 'Mittlere Events' },
    ],
  },
  {
    id: 'inverter-stromerzeuger-6kw',
    name: 'Inverter Stromerzeuger 6 kW',
    description: 'Leistungsstarker Inverter-Stromerzeuger mit 6 kW Leistung. Für große Veranstaltungen.',
    images: ['/images/hy3200si_1-1920w.jpg'],
    pricePerUnit: 120,
    categorySlug: 'stromerzeuger',
    specs: [
      { label: 'Leistung', value: '6 kW' },
      { label: 'Typ', value: 'Inverter' },
      { label: 'Anwendung', value: 'Große Events' },
    ],
  },

  // Bühnenpodeste & Traversen
  {
    id: 'rednerpodest-drumriser',
    name: 'Rednerpodest / Drumriser',
    description: 'Vielseitiges Podest für Redner oder als Drumriser für Schlagzeuger. Höhenverstellbar.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 30,
    categorySlug: 'buehlenpodeste-traversen',
    specs: [
      { label: 'Typ', value: 'Rednerpodest / Drumriser' },
      { label: 'Anwendung', value: 'Redner / Schlagzeug' },
      { label: 'Höhe', value: 'Verstellbar' },
    ],
  },
  {
    id: 'buehne-4x3m',
    name: 'Bühne 4x3 m',
    description: 'Modulare Bühne mit 4x3 Meter Grundfläche. Professionelle Bühnenkonstruktion.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 200,
    categorySlug: 'buehlenpodeste-traversen',
    specs: [
      { label: 'Größe', value: '4x3 Meter' },
      { label: 'Fläche', value: '12 m²' },
      { label: 'Typ', value: 'Modular' },
    ],
  },
  {
    id: 'faltpavillion',
    name: 'Faltpavillion',
    description: 'Praktischer Faltpavillion für Outdoor-Events. Schnell auf- und abbaubar.',
    images: ['/images/ixstage5-1920w.jpg'],
    pricePerUnit: 150,
    categorySlug: 'buehlenpodeste-traversen',
    specs: [
      { label: 'Typ', value: 'Faltpavillion' },
      { label: 'Aufbau', value: 'Schnell' },
      { label: 'Anwendung', value: 'Outdoor' },
    ],
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter(product => product.categorySlug === categorySlug);
}

export function getProductById(id: string): Product | undefined {
  return products.find(product => product.id === id);
}
